### ISSUE TITLE
Can't make it work withe example code

### ISSUE THREAD

**Issue by Ch00k** [emersion/go-imap-idle#3]
I'm using the following code:
```go
package main

import (
	"log"
	"os"

	"github.com/emersion/go-imap"
	"github.com/emersion/go-imap-idle"
	"github.com/emersion/go-imap/client"
)

const (
	address  = "foo"
	username = "bar"
	password = "baz"
	mailbox  = "INBOX"
)

func main() {
	c, _ := client.DialTLS(address, nil)
	c.SetDebug(os.Stdout)

	c.Login(username, password)
	c.Select(mailbox, true)

	statuses := make(chan *imap.MailboxStatus)
	c.MailboxUpdates = statuses

	idleClient := idle.NewClient(c)

	stop := make(chan struct{})
	done := make(chan error, 1)

	go func() {
		done <- idleClient.Idle(stop)
	}()

	for {
		select {
		case status := <-statuses:
			log.Println("New mailbox status:", status)
			close(stop)
		case err := <-done:
			if err != nil {
				log.Fatal(err)
			}
			log.Println("Not idling anymore")
			return
		}
	}
}
```
I run this code and mark one of the messages in INBOX as unread. This results in the following output:
```
zg9unQ LOGIN bar baz
G_2kiA EXAMINE INBOX
* FLAGS (\Answered \Flagged \Deleted \Seen \Draft unknown-2 unknown-5 unknown-1 unknown-6 unknown-8 unknown-0 $NotJunk $Junk JunkRecorded unknown-7 NotJunk $Forwarded $MDNSent)
* OK [PERMANENTFLAGS ()] Read-only mailbox.
* 14570 EXISTS
* 0 RECENT
* OK [UIDVALIDITY 1394450969] UIDs valid
* OK [UIDNEXT 25420] Predicted next UID
* OK [HIGHESTMODSEQ 59666] Highest
G_2kiA OK [READ-ONLY] Examine completed (0.000 + 0.000 secs).
imap/client: 2016/11/03 09:09:31 response has not been handled: &{* OK HIGHESTMODSEQ [59666] Highest}
tVJIGQ IDLE
+ idling
* 14570 FETCH (FLAGS ())
```
The line `* 14570 FETCH (FLAGS ())` is what is printed when I mark the message as unread. But no code inside of the `for` loop is executed.

**Comment by emersion** [comment]
When you mark a message as unseen, it's not the same as when you receive a new message in your inbox. Marking a message sends a message update, appending a message to a mailbox sends a mailbox status. Here the example only listens for mailbox updates.

Listening for message updates is not yet supported, see https://github.com/emersion/go-imap/issues/5. I'll fix that this afternoon.

**Comment by Ch00k** [comment]
I tried it with a new message, but it still does not trigger any code inside the `for` loop. What I see in the log now is this:

```
* 14573 EXISTS
* 1 RECENT
```

**Comment by emersion** [comment]
Yes, some changes in go-imap broke it. Should be fixed now!

**Comment by emersion** [comment]
Info: support for unilateral message updates has just been added, so you should now be able to use `c.MessageUpdates` just as `c.MailboxUpdates`.
