### ISSUE TITLE
Connection goes stale.

### ISSUE THREAD

**Issue by ggitau** [emersion/go-imap-idle#5]
My idle client has been running for a few days. During that period I might have disconnected from the internet a couple of times. The connection does not timeout or send an error via the done channel and no new messages are received. It works only after I restart it. It seems that the connection went stale. Is there some sort of timeout mechanism I can use to determine when I need to re-establish the connection? I did get a "imap: connection closed" error once but not this time.

**Comment by emersion** [comment]
You can set [`Client.Timeout`](https://godoc.org/github.com/emersion/go-imap/client#Client.Timeout) if you want. The `done` channel is closed when `Read` returns an error, don't know if I can do anything else to detect when connections are closed.

**Comment by ggitau** [comment]
I think this is where i might have been going wrong...I need to reconnect every 29 or so minutes..
[https://tools.ietf.org/html/rfc2177](url)

>  The server MAY consider a client inactive if it has an IDLE command
>    running, and if such a server has an inactivity timeout it MAY log
>    the client off implicitly at the end of its timeout period.  Because
>    of that, clients using IDLE are advised to terminate the IDLE and
>    re-issue it at least every 29 minutes to avoid being logged off.
>    This still allows a client to receive immediate mailbox updates even
>    though it need only "poll" at half hour intervals.

**Comment by emersion** [comment]
Yeah, you need to stop idling and send a new `IDLE` command each 29 minutes. Here is an example:

https://github.com/emersion/neutron/blob/65865f9df3c58711afa6eadf29ff2d9d2ddcc1e7/backend/imap/conn.go#L170

I updated the README to warn about this.

**Comment by ggitau** [comment]
@emersion Thanks
