### ISSUE TITLE
Is the done channel closed internally?

### ISSUE THREAD

**Issue by ggitau** [emersion/go-imap-idle#6]
Hi,
Does the `client.Idle` method close the done channel internally?I am trying to close it so that I can logout but I end up with a "close of closed channel"  panic.

**Comment by emersion** [comment]
The `done` channel type is `<-chan struct{}` so values can only be received from it (the `Idle` method cannot send values or close it). It's most likely an issue with your code.

**Comment by ggitau** [comment]
@emersion Alright.Thanks
